# Generated by Django 6.0.5 on 2026-06-02 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk_index', models.PositiveIntegerField()),
                ('content', models.TextField()),
                ('token_count', models.PositiveIntegerField(default=0)),
                ('page_number', models.PositiveIntegerField(blank=True, null=True)),
                ('section_title', models.CharField(blank=True, max_length=240)),
                ('source_metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='documents.document')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_chunks', to='workspaces.workspace')),
            ],
            options={
                'ordering': ['document_id', 'chunk_index'],
                'indexes': [models.Index(fields=['workspace', 'document'], name='documents_d_workspa_714890_idx'), models.Index(fields=['workspace', 'chunk_index'], name='documents_d_workspa_b48acf_idx')],
                'constraints': [models.UniqueConstraint(fields=('document', 'chunk_index'), name='unique_document_chunk_index')],
            },
        ),
    ]
