# Generated by Django 6.0.5 on 2026-06-02 18:02

import pgvector.django.vector
from django.db import migrations, models
from pgvector.django import VectorExtension


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_documentchunk'),
        ('workspaces', '0001_initial'),
    ]

    operations = [
        VectorExtension(),
        migrations.AddField(
            model_name='documentchunk',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=1536, null=True),
        ),
        migrations.AddField(
            model_name='documentchunk',
            name='embedding_model',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddIndex(
            model_name='documentchunk',
            index=models.Index(fields=['workspace', 'embedding_model'], name='documents_d_workspa_6ffd93_idx'),
        ),
    ]
