# Generated by Django 6.0.5 on 2026-06-03 07:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chat', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.CharField(choices=[('up', 'Thumbs up'), ('down', 'Thumbs down')], max_length=10)),
                ('comment', models.TextField(blank=True)),
                ('failure_tag', models.CharField(blank=True, choices=[('wrong_answer', 'Wrong answer'), ('missing_citation', 'Missing citation'), ('weak_citation', 'Weak citation'), ('hallucination', 'Hallucination'), ('outdated_source', 'Outdated source'), ('unclear_answer', 'Unclear answer'), ('access_issue', 'Access issue'), ('other', 'Other')], max_length=40)),
                ('reviewed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='chat.chatmessage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_feedback', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['rating', 'created_at'], name='feedback_an_rating_abfd4f_idx'), models.Index(fields=['reviewed', 'created_at'], name='feedback_an_reviewe_bc072c_idx'), models.Index(fields=['failure_tag', 'created_at'], name='feedback_an_failure_8678e0_idx')],
                'constraints': [models.UniqueConstraint(fields=('message', 'user'), name='unique_answer_feedback_per_user')],
            },
        ),
    ]
