# Generated by Django 6.0.5 on 2026-06-03 13:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workspaces', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180)),
                ('dataset_name', models.CharField(max_length=180)),
                ('model_name', models.CharField(blank=True, max_length=120)),
                ('retrieval_top_k', models.PositiveIntegerField(default=8)),
                ('status', models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='running', max_length=20)),
                ('average_retrieval_recall', models.FloatField(default=0.0)),
                ('average_citation_precision', models.FloatField(default=0.0)),
                ('average_faithfulness', models.FloatField(default=0.0)),
                ('average_answer_relevance', models.FloatField(default=0.0)),
                ('abstention_accuracy', models.FloatField(default=0.0)),
                ('average_latency_ms', models.PositiveIntegerField(default=0)),
                ('p50_latency_ms', models.PositiveIntegerField(default=0)),
                ('p95_latency_ms', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evaluation_runs', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_runs', to='workspaces.workspace')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EvaluationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('expected_answer', models.TextField(blank=True)),
                ('answer', models.TextField(blank=True)),
                ('expected_sources', models.JSONField(blank=True, default=list)),
                ('retrieved_sources', models.JSONField(blank=True, default=list)),
                ('cited_sources', models.JSONField(blank=True, default=list)),
                ('should_abstain', models.BooleanField(default=False)),
                ('retrieval_recall', models.FloatField(default=0.0)),
                ('citation_precision', models.FloatField(default=0.0)),
                ('faithfulness', models.FloatField(default=0.0)),
                ('answer_relevance', models.FloatField(default=0.0)),
                ('abstention_correct', models.BooleanField(default=False)),
                ('latency_ms', models.PositiveIntegerField(default=0)),
                ('model_name', models.CharField(blank=True, max_length=120)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='evaluations.evaluationrun')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='evaluationrun',
            index=models.Index(fields=['workspace', '-created_at'], name='evaluations_workspa_4cbebc_idx'),
        ),
        migrations.AddIndex(
            model_name='evaluationrun',
            index=models.Index(fields=['status', '-created_at'], name='evaluations_status_7ef4a8_idx'),
        ),
        migrations.AddIndex(
            model_name='evaluationresult',
            index=models.Index(fields=['run', 'retrieval_recall'], name='evaluations_run_id_d2a898_idx'),
        ),
        migrations.AddIndex(
            model_name='evaluationresult',
            index=models.Index(fields=['run', 'faithfulness'], name='evaluations_run_id_f930bb_idx'),
        ),
    ]
